name: chatapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.3.8
  firebase_core: 1.10.0
  google_sign_in: 5.2.1
  firebase_auth: 3.2.0
  lottie: 1.2.1
  introduction_screen: 2.1.0
  google_fonts: ^2.1.0
  avatar_glow: 2.0.2
  cloud_firestore: 3.1.0
  firebase_storage: 10.1.0
  emoji_picker_flutter: 1.0.7
  get_storage: 2.0.3
  intl: 0.17.0
  image_picker: 0.8.4+4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_launcher_icons: ^0.9.2
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/logo/icon.png
  ios: true

flutter: 
  assets: 
    - assets/lottie/
    - assets/logo/
  uses-material-design: true

